steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo 'NEXT_PUBLIC_FRONT_URL="${_NEXT_PUBLIC_FRONT_URL}"' >> .env
        echo 'NEXT_PUBLIC_GOOGLE_ANALYTICS_ID="${_NEXT_PUBLIC_GOOGLE_ANALYTICS_ID}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_API_KEY="${_NEXT_PUBLIC_FIREBASE_API_KEY}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN="${_NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_PROJECT_ID="${_NEXT_PUBLIC_FIREBASE_PROJECT_ID}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET="${_NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}"' >> .env
        echo 'NEXT_PUBLIC_FIREBASE_APP_ID="${_NEXT_PUBLIC_FIREBASE_APP_ID}"' >> .env
        cat .env

  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-t'
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
    id: Push

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - --platform=managed
      - --image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA
      - --labels=commit-sha=$COMMIT_SHA
      - --region=$_DEPLOY_REGION
      - --concurrency=1000
      - --cpu=1
      - --memory=4096Mi
      - --max-instances=1
      - --min-instances=0
      - --no-traffic
      - --no-cpu-throttling
      - --ingress=all
      - --update-secrets=FIREBASE_ADMIN_PROJECT_ID=FIREBASE_ADMIN_PROJECT_ID:latest
      - --update-secrets=FIREBASE_ADMIN_CLIENT_EMAIL=FIREBASE_ADMIN_CLIENT_EMAIL:latest
      - --update-secrets=FIREBASE_ADMIN_PRIVATE_KEY=FIREBASE_ADMIN_PRIVATE_KEY:latest
      - --quiet
    id: Deploy
    entrypoint: gcloud

timeout: 1800s

substitutions:
  _GCR_HOSTNAME: asia.gcr.io
  _SERVICE_NAME: frontend
  _DEPLOY_REGION: asia-northeast1
